/*
 * ListAndChooseRoots.java
 *
 * Created on 16 de Abril de 2008, 20:05
 */
package de.berlios.jfindmyfiles.spklerdados;

import java.io.File;
import java.util.Vector;
import javax.swing.JToggleButton;

/**
 *
 * @author  ei10635
 */
public class ListAndChooseRoots extends javax.swing.JFrame {

    /** Creates new form ListAndChooseRoots */
    private Vector<JToggleButton> buttons;
    
    public ListAndChooseRoots() {
        initComponents();
    }
    
    private void listAllDrivesAndFirstLevelContent() {
        for (File f : File.listRoots()) {
            System.out.println(f.getAbsolutePath());
            File[] list = f.listFiles();
            if (list != null) {
                for (File f2 : list) {
                    System.out.println(f2.getName());
                }
            }
            
        }        
    }

    private void listAndAdd() {
        for (File f : File.listRoots()) {
            System.out.println(f.getAbsolutePath());
            JToggleButton jtb = new JToggleButton(f.getAbsolutePath());
            jpResults.add(jtb);
            buttonGroup1.add(jtb);
        }
        jpResults.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbtList = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jpResults = new javax.swing.JPanel();
        jbtClear = new javax.swing.JButton();
        jbtClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtList.setText("List");
        jbtList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListActionPerformed(evt);
            }
        });

        jpResults.setLayout(new javax.swing.BoxLayout(jpResults, javax.swing.BoxLayout.LINE_AXIS));

        jbtClear.setText("Clear");
        jbtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearActionPerformed(evt);
            }
        });

        jbtClose.setText("Close");
        jbtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpResults, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtList)
                    .addComponent(jbtClear)
                    .addComponent(jbtClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpResults, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jbtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCloseActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jbtCloseActionPerformed

    private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
        jpResults.removeAll();
        jpResults.validate();
    }//GEN-LAST:event_jbtClearActionPerformed

    private void jbtListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListActionPerformed
        listAndAdd();
    }//GEN-LAST:event_jbtListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListAndChooseRoots().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtClear;
    private javax.swing.JButton jbtClose;
    private javax.swing.JButton jbtList;
    private javax.swing.JPanel jpResults;
    // End of variables declaration//GEN-END:variables
}
