/**
 *  Copyright (C) 2008  Patrícia Monteiro e Sérgio Lopes
 *
 *  This file is part of JFindMyFiles.
 *
 *  JFindMyFiles is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  JFindMyFiles is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with JFindMyFiles.  If not, see 
 * <http://www.gnu.org/licenses/gpl.html>.
 */
package de.berlios.jfindmyfiles.jfindmyfilesgui.dialogs;

import de.berlios.jfindmyfiles.readingfiles.MediaReader;
import de.berlios.jfindmyfiles.readingfiles.ReadingEvent;
import de.berlios.jfindmyfiles.readingfiles.ReadingListener;
import javax.swing.SwingUtilities;
import org.openide.util.Lookup;
import org.openide.windows.WindowManager;

/**
 *
 * @author  ei10635
 */
public class ActiveScanningDlg extends javax.swing.JDialog implements ReadingListener {

    private NewDiskDlg nDskDlg;
    private boolean ask4desc;
    private boolean showAgain;
    private boolean stop = true;
    private ActiveScanningDlg me = this;

    /** Creates new form ActiveScanningDlg */
    public ActiveScanningDlg(java.awt.Frame parent, boolean modal, NewDiskDlg nDskDlg) {
        super(parent, modal);
        this.nDskDlg = nDskDlg;
        initComponents();
    }

    public void showCentered(boolean ask4desc, boolean showAgain) {
        this.ask4desc = ask4desc;
        this.showAgain = showAgain;
        setLocation(getParent().getX() + (getParent().getWidth() / 2) - (getWidth() / 2),
                getParent().getY() + (getParent().getHeight() / 2) - (getHeight() / 2));
        setVisible(true);
    }

    public void advance() {
        stop = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpbReadingProgress = new javax.swing.JProgressBar();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        jpbReadingProgress.setIndeterminate(true);
        jpbReadingProgress.setString(org.openide.util.NbBundle.getMessage(ActiveScanningDlg.class, "ActiveScanningDlg.jpbReadingProgress.string")); // NOI18N
        jpbReadingProgress.setStringPainted(true);

        jbtnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/jfindmyfiles/jfindmyfilesgui/resources/images/x16/button-stop.png"))); // NOI18N
        jbtnCancel.setText(org.openide.util.NbBundle.getMessage(ActiveScanningDlg.class, "ActiveScanningDlg.jbtnCancel.text")); // NOI18N
        jbtnCancel.setFocusPainted(false);
        jbtnCancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtnCancel.setMaximumSize(new java.awt.Dimension(20, 19));
        jbtnCancel.setMinimumSize(new java.awt.Dimension(20, 19));
        jbtnCancel.setPreferredSize(new java.awt.Dimension(20, 19));
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpbReadingProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpbReadingProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
    MediaReader r = Lookup.getDefault().lookup(MediaReader.class);
    r.abort();
}//GEN-LAST:event_jbtnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JProgressBar jpbReadingProgress;
    // End of variables declaration//GEN-END:variables
    public void readingStarted(ReadingEvent evt) {
        //DO NOTHING
    }

    public void readingFile(ReadingEvent evt) {
        jpbReadingProgress.setString(evt.getCurrentFileName());
    }

    @SuppressWarnings("empty-statement")
    public void readingStopped(final ReadingEvent evt) {
        //NOTE: look for concurrent modification
        Lookup.getDefault().lookup(MediaReader.class).removeListener(this);
        if (ask4desc) {
            SwingUtilities.invokeLater(new Runnable() {

                public void run() {
                    setVisible(false);
                    stop = true;
                    new AskDescriptionDlg(WindowManager.getDefault().getMainWindow(), true, me, evt.getMedia()).showCentered();
                }
            });
        }

        dispose();
        //NOTE: can this code really block the execution, infinite loop?
        while (stop);
        if (showAgain) {
            nDskDlg.setVisible(true);
        }
    }

    public void readingAborted(ReadingEvent evt) {
        readingStopped(evt);
    }
}
