/*
 * NewDiscJDialog.java
 *
 * Created on 29 de Abril de 2008, 14:18
 */

package de.berlios.jfindmyfiles.jfindmyfilesgui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author  ei10635
 */
public class NewDiscJDialog extends javax.swing.JDialog {
    
    /** Creates new form NewDiscJDialog */
    public NewDiscJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
    }
    
    /** Creates toggle buttons and adds them to the top panel. The buttons will 
     * have the icon given to the drive by the OS and the name provided by the 
     * absolute path.
     * 
     * All buttons are added to a button group so that no two buttons can be 
     * selected at the same time.
     */
    private void createDriveButtons() {
        FileSystemView fsv = FileSystemView.getFileSystemView();
        File[] roots = File.listRoots();
        
        JToggleButton toggle;
        for(int i = 0; i < roots.length; i++) {      
            toggle = new JToggleButton(roots[i].getAbsolutePath(), fsv.getSystemIcon(roots[i]));
            toggle.setHorizontalTextPosition(SwingConstants.CENTER);
            toggle.addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                    toggleDriveAction();//NOTE: will most likely be removed
                }
            });
            jbtngrpDrives.add(toggle);
            jpButtons.add(toggle);
        }
        
        jpButtons.validate();
    }
    
    /** Provides the action for the toggle buttons with the drive names.
     * Gets the selected drive from the name of the selected button in the 
     * button group.
     */
    private void toggleDriveAction() {     
        //TODO: add suport for choosing the drive
        throw new UnsupportedOperationException("Not implemented yet");
    }
    
    private String[] listOpenCatalogs() {
        //TODO: get open catalog list and return a useful structure to be used 
        //by a JComboBox
        throw new UnsupportedOperationException("Not implemented yet");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtngrpDrives = new javax.swing.ButtonGroup();
        jpButtons = new javax.swing.JPanel();
        createDriveButtons();
        jlblDiskNumber = new javax.swing.JLabel();
        jffDiskNumber = new javax.swing.JFormattedTextField();
        jlblDiskName = new javax.swing.JLabel();
        jtfDiskName = new javax.swing.JTextField();
        jcbxCatalog = new javax.swing.JComboBox();
        jlblCatalog = new javax.swing.JLabel();
        jpScanningOptions = new javax.swing.JPanel();
        jchkCalculateCRC = new javax.swing.JCheckBox();
        jchkAskDescription = new javax.swing.JCheckBox();
        jchkShowAgain = new javax.swing.JCheckBox();
        jbtnHelp = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jbtnStart = new javax.swing.JButton();
        jbtnSelectedPlugins = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlblDiskNumber.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jlblDiskNumber.text")); // NOI18N

        jffDiskNumber.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jffDiskNumber.text")); // NOI18N

        jlblDiskName.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jlblDiskName.text")); // NOI18N

        jtfDiskName.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jtfDiskName.text")); // NOI18N

        jcbxCatalog.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblCatalog.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jlblCatalog.text")); // NOI18N

        jpScanningOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jpScanningOptions.border.title"))); // NOI18N

        jchkCalculateCRC.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jchkCalculateCRC.text")); // NOI18N

        jchkAskDescription.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jchkAskDescription.text")); // NOI18N

        jchkShowAgain.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jchkShowAgain.text")); // NOI18N

        javax.swing.GroupLayout jpScanningOptionsLayout = new javax.swing.GroupLayout(jpScanningOptions);
        jpScanningOptions.setLayout(jpScanningOptionsLayout);
        jpScanningOptionsLayout.setHorizontalGroup(
            jpScanningOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpScanningOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpScanningOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkCalculateCRC)
                    .addComponent(jchkAskDescription)
                    .addComponent(jchkShowAgain))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jpScanningOptionsLayout.setVerticalGroup(
            jpScanningOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpScanningOptionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jchkCalculateCRC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkAskDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkShowAgain))
        );

        jbtnHelp.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jbtnHelp.text")); // NOI18N

        jbtnCancel.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jbtnCancel.text")); // NOI18N

        jbtnStart.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jbtnStart.text")); // NOI18N

        jbtnSelectedPlugins.setText(org.openide.util.NbBundle.getMessage(NewDiscJDialog.class, "NewDiscJDialog.jbtnSelectedPlugins.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpScanningOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jffDiskNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblDiskNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDiskName, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jlblDiskName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCatalog)
                            .addComponent(jcbxCatalog, 0, 135, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnSelectedPlugins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jbtnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnHelp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCatalog)
                    .addComponent(jlblDiskName)
                    .addComponent(jlblDiskNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jffDiskNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDiskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpScanningOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnHelp)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnStart)
                    .addComponent(jbtnSelectedPlugins))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnHelp;
    private javax.swing.JButton jbtnSelectedPlugins;
    private javax.swing.JButton jbtnStart;
    private javax.swing.ButtonGroup jbtngrpDrives;
    private javax.swing.JComboBox jcbxCatalog;
    private javax.swing.JCheckBox jchkAskDescription;
    private javax.swing.JCheckBox jchkCalculateCRC;
    private javax.swing.JCheckBox jchkShowAgain;
    private javax.swing.JFormattedTextField jffDiskNumber;
    private javax.swing.JLabel jlblCatalog;
    private javax.swing.JLabel jlblDiskName;
    private javax.swing.JLabel jlblDiskNumber;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JPanel jpScanningOptions;
    private javax.swing.JTextField jtfDiskName;
    // End of variables declaration//GEN-END:variables
    
}
